namers:
- kind: io.l5d.consul
  host: consul
  includeTag: false

admin:
  port: 9990
  ip: 0.0.0.0

routers:

# This service proxies traffic to services looked up in consul
- protocol: http
  service:
    kind: io.l5d.global
    responseClassifier:
      kind: io.l5d.http.retryableIdempotent5XX
    retries:
      budget:
        percentCanRetry: 2.0

  label: http
  identifier:
    kind: io.l5d.path
    segments: 1
    consume: true
  dtab: |
    /svc => /#/io.l5d.consul/dc1;
  servers:
  - port: 4140
    ip: 0.0.0.0

telemetry:
- kind: io.l5d.prometheus

usage:
  orgId: linkerd-demo
