version: '3'
services:

  consul:
    image: consul:1.0.2
    ports:
      - 8500:8500

  consul-registrator:
    image: gliderlabs/registrator:v7
    command: ['-internal', 'consul://consul:8500']
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  service-a-b:
    image: buoyantio/slow_cooker:1.0.1
    entrypoint: /bin/sh
    command: >
      -c 'sleep 15 && export SERVICE_TAGS=foo  && slow_cooker -qps 20 -concurrency 15 -interval 5s -totalRequests 100000000 http://linkerd:4140/service-a'
    depends_on:
      - service-b

  service-a-c:
    image: buoyantio/slow_cooker:1.0.1
    entrypoint: /bin/sh
    command: >
      -c 'sleep 15 && slow_cooker -qps 20 -concurrency 15 -interval 5s -totalRequests 100000000 http://linkerd:4140/service-b'
    depends_on:
      - service-b

  linkerd:
    image: buoyantio/linkerd:1.3.5
    depends_on:
      - consul
      - consul-registrator
    volumes:
      - ./linkerd/config.yml:/config.yml
    command: /config.yml
    ports:
      - 4140:4140
      - 9990:9990

  linkerd-viz:
    build: ./linkerd-viz
    image: buoyantio/linkerd-viz:0.1.7
    command: ['consul']
    depends_on:
      - linkerd
      - consul
      - consul-registrator
    ports:
      - 3000:3000
      - 9191:9191
    environment:
      - CONSUL_HOST=consul
    volumes:
      - ./linkerd-viz/config.yml:/etc/prometheus/prometheus-consul.yml:ro

  service-b:
    build: ./echo
    depends_on:
      - linkerd
    command: -success-rate=0.6
    ports:
      - 8501
    environment:
      - SERVICE_8501_NAME=service-a

  service-c:
    build: ./echo
    depends_on:
      - linkerd
    command: -success-rate=0.9
    ports:
      - 8501
    environment:
      - SERVICE_8501_NAME=service-b
